depends:
project:
  name: tutorial
  debug: true
logger:
  format:
    prefix: tutorial
web:
  port: 8080
  host: 0.0.0.0
  url: http://localhost
  timeout:
    read: 60
    write: 60
    idle: 60
db:
  sslMode: disable
  maxConnections: 50
  connectionIdleLifetime: 15
rabbit:
  queues:
    tutorial.test:
      exchange: amq.direct
      type: direct
      routingKey:
        - tutorial-test-message
      durable: true
    tutorial.event:
      exchange: amq.direct
      type: direct
      routingKey:
        - tutorial-event
      durable: true
arguments:
  app:
    type: string
    label: application type
  name:
    type: string
    label: name of script
  file:
    type: string
    label: name of file
  class:
    type: string
    label: type of entity
  queue:
    type: string
    label: name of the queue
  server:
    type: string
    label: name of the server
  num:
    type: int
    label: number of something
  color:
    type: string
    label: custom parameter color