depends: global
db:
  host: 0.0.0.0
  port: 5432
  name: tutorial
  user: tutorial
  password: tutorial
rabbit:
  servers:
    local:
      host: 0.0.0.0
      vhost: \
      port: 5672
      user: tutorial
      password: admin
